### ISSUE TITLE
Using flexbox instead of floating grid

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/tendrl_frontend#6]
Reasons - 
- Flexbox  is content driven model. It does not need to know the content upfront.
- Contents can be redistributed. 
- Allow boxes to wrap which is really handy for responsive design.

**Comment by nthomas-redhat** [comment]
why not patternfly? Is there any issues/challenges?

**Comment by shtripat** [comment]
Also as per guidelines from UX team, UI has to be patternfly compliant.

**Comment by gnehapk** [comment]
Patternfly provides us with good grid system which is good and suitable in dashboards and other form pages, but when it comes to the listing pages a good number of alignment issues has been faced in the skyrings web interface. Currently patternfly relies on Bootstrap grid system, which is based on floats. We do want to use patternfly for all the features it brings, but not having flexbox layouts are only concern against it.

**Comment by kmkanagaraj** [comment]
@gnehapk you can talk to Patternfly team to understand their plan of action for moving to flexbox. So that you can take approach of using flexbox on required page and move them patternfly once the support is available. Also flexbox support in bootstrap is around the corner.

http://v4-alpha.getbootstrap.com/getting-started/flexbox/

Everything aside, patternfly team puts lot of effort in satisfying the requirements of the consumers(like tendrl).

**Comment by nthomas-redhat** [comment]
Thanks @gnehapk , @kmkanagaraj  
@julienlim, can we have someone from the patternfly team here to understand the plans on this and see  whether it is aligning with tendrl upstream release plans? or can you give some insights on this?

**Comment by debloper** [comment]
To add some more details here (conversation progressed through emails, thanks to @julienlim):
- The patternfly team did address their motif to base on top of BS4 in near future.
- The timeline of availability is unknown/TBA (need update, when available)
- All things considered, we might have to stick with floating grids for now.
